#!/bin/bash
git config --global core.editor "nano"
git config --global user.name "Sean Hayes"
git config --global user.email gasphynx@gmail.com
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.last 'log -1 HEAD'